production: 'https://restcountries.eu/rest/v2'

staging: 'https://restcountries.eu/rest/v2'

test:  'https://restcountries.eu/rest/v2'

development: 'https://restcountries.eu/rest/v2'

all_countries: '/all'

italy: '/name/italy'

